[package]
name = "reaction_diffusion"
version = "0.1.0"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[dependencies]
nannou = "0.11.1"
nannou_utils = { path = "../nannou_utils" }
rand = "0.7.2"
